version: '3.8'

services:
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./volumes/mysql/db:/var/lib/mysql
      - ./volumes/mysql/scripts:/docker-entrypoint-initdb.d
  
  grafana:
    image: grafana/grafana
    env_file: .env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
      - GF_USERS_ALLOW_SIGN_UP=$GF_USERS_ALLOW_SIGN_UP
      - GF_AUTH_ANONYMOUS_ENABLED=$GF_AUTH_ANONYMOUS_ENABLED
    user: "472"
    #depends_on:
    #  - 
    ports:
      - $GF_LOCAL_PORT:$GF_DOCKER_PORT
    volumes:
      - ./volumes/grafana/provisioning/:/etc/grafana/provisioning/
    restart: always

  qourier_app:
    depends_on:
      - mysqldb
      - grafana
    build: ./qourier_app
    env_file: ./.env
    ports:
      - $SPRING_QOURIER_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - ./volumes/quorier/:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: