version: '3.8'

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./volumes/mysql/db:/var/lib/mysql
      - ./volumes/mysql/scripts:/docker-entrypoint-initdb.d

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    volumes:
      - ./volumes/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
      - GF_USERS_ALLOW_SIGN_UP=$GF_USERS_ALLOW_SIGN_UP
      - GF_AUTH_ANONYMOUS_ENABLED=$GF_AUTH_ANONYMOUS_ENABLED
      - GF_INSTALL_PLUGINS:"flant-statusmap-panel,grafana-piechart-panel"
      - GF_SECURITY_ALLOW_EMBEDDING=true
    depends_on:
      - prometheus
    ports:
      - $GF_LOCAL_PORT:$GF_DOCKER_PORT
    volumes:
      - ./volumes/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/rabbitmq.yaml
      - ./volumes/grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./volumes/grafana/dashboards:/dashboards
    restart: always

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674
      - 15692:15692 # Used for prometheus metrics
    volumes:
      - ./volumes/rabbitmq/:/etc/rabbitmq/
    command: [sh, -c, "rabbitmq-plugins enable rabbitmq_web_stomp rabbitmq_prometheus rabbitmq_management && rabbitmq-server"]

  qourier_app:
    depends_on:
      - mysqldb
      - rabbitmq
      - grafana
    build: ./qourier_app
    ports:
      - $SPRING_QOURIER_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.datasource.adminemail" : "$ADMIN_EMAIL",
            "spring.datasource.adminpass" : "$ADMIN_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    volumes:
      - ./volumes/qourier/:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
  prometheus-data:
