name: Auto assign Product Owner to Pull Requests

on:
  pull_request:
    branches: [ qourier_dev, laundryathome_dev ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - name: Auto assign Product Owner as reviewer
      uses: kentaro-m/auto-assign-action@v1.2.1
