name: Auto release

on:
  schedule:
    - cron: '0 0 * * 2'
  push:
    branches: [ ci-setup ]
  
jobs:
  update-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: release
        fetch-depth: 0
    - name: Merge the Qourier development branch
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: qourier_dev
        target_branch: release
        github_token: ${{ github.token }}
    - name: Merge the LaundryAtHome development branch
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: laundryathome_dev
        target_branch: release
        github_token: ${{ github.token }}
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_prefix: "AUTO RELEASE"
    - name: Create pull request
      uses: devops-infra/action-pull-request@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        title: AUTO RELEASE
        target_branch: main
        reviewer: tomascandeias
    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v4
    #   with:
    #     branch: main
    #     title: Auto release PR
    #     reviewers: tomascandeias
