name: LaundryAtHome

on:
  pull_request:
    branches: [ laundryathome_dev ]

jobs:
  verify:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: LaundryAtHome/LaundryPlatform

    steps:
    - uses: actions/checkout@v3
      with:
          ref: ${{ github.event.pull_request.head.ref }}    # for Google Java Format auto format commits
          fetch-depth: 0    # Shallow clones should be disabled for a better relevancy of analysis
    - name: Google Java Format enforcer, without imports
      uses: axel-op/googlejavaformat-action@v3
      with:
        skipCommit: true
        files: "LaundryAtHome/LaundryPlatform/**/*.java"
        args: "--aosp --skip-sorting-imports --skip-removing-unused-imports --dry-run --set-exit-if-changed"
    - name: Google Java Format import structure fixer
      uses: axel-op/googlejavaformat-action@v3
      if: always()
      with:
        files: "LaundryAtHome/LaundryPlatform/**/*.java"
        commitMessage: Google Java Format import ordering
        args: "--fix-imports-only --replace"
    - name: Set up OpenJDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify jacoco:prepare-agent jacoco:report org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Afonso-Boto_TQS_LaundryDelivery -Pcoverage
    - name: Test report
      uses: dorny/test-reporter@v1
      if: always()
      with:
          name: Maven tests
          path: LaundryAtHome/LaundryPlatform/target/surefire-reports/TEST-*.xml
          reporter: java-junit
          fail-on-error: true
    - name: Auto assign all devs as reviewers
      uses: kentaro-m/auto-assign-action@v1.2.1
      if: always()
      with:
        configuration-path: '.github/auto_assign_laundryathome.yml'
