name: Qourier

on:
  pull_request:
    branches: [ qourier_dev ]

jobs:
  verify:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: Qourier/qourier_app

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0    # Shallow clones should be disabled for a better relevancy of analysis
    - name: Set up OpenJDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build and analyze
      run: mvn -B verify
    - name: Test report
      uses: dorny/test-reporter@v1
      if: always()
      with:
          name: Maven tests
          path: Qourier/qourier_app/target/surefire-reports/TEST-*.xml
          reporter: java-junit
          fail-on-error: true
    - name: Auto assign Product Owner as reviewer
      uses: kentaro-m/auto-assign-action@v1.2.1
